In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('Titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.drop(['PassengerId','Name','Ticket'],axis= 1, inplace=True)

df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [ ]:
# def drop_columns(df,columns):
#     return df.drop(columns=columns)

In [ ]:
# drop_col = ['PassengerId','Name','Ticket']
# drop_columns(df,drop_col)

In [16]:
dtypes= df.dtypes
n_unique = df.nunique()

pd.DataFrame({"Dtype ":dtypes,"N_unique ":n_unique})

           Dtype   N_unique
Survived    int64          2
Pclass      int64          3
Sex           str          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin         str        147
Embarked      str          3

In [17]:
null = df.isnull().sum()
ratio = (null/df.shape[0]) *100
pd.DataFrame({"null ":null,"ratio ":ratio})

          null      ratio
Survived      0   0.000000
Pclass        0   0.000000
Sex           0   0.000000
Age         177  19.865320
SibSp         0   0.000000
Parch         0   0.000000
Fare          0   0.000000
Cabin       687  77.104377
Embarked      2   0.224467

In [19]:
df = df.dropna(subset=['Embarked'])

In [20]:
df = df.drop('Cabin',axis=1)

In [21]:
median = df['Age'].median()
df['Age']=df['Age'].fillna(median)

In [22]:
null = df.isnull().sum()
ratio = (null/df.shape[0]) *100
pd.DataFrame({"null ":null,"ratio ":ratio})

          null   ratio
Survived      0     0.0
Pclass        0     0.0
Sex           0     0.0
Age           0     0.0
SibSp         0     0.0
Parch         0     0.0
Fare          0     0.0
Embarked      0     0.0

In [ ]:
cols = ['Survived','Pclass','Sex','SibSp','Parch','Embarked']
df[cols]=df[cols].astype('category')
df.dtypes

Survived    category
Pclass      category
Sex         category
Age          float64
SibSp       category
Parch       category
Fare         float64
Embarked    category
dtype: object

In [25]:
num_cols = df.select_dtypes('number').columns
num_cols

Index(['Age', 'Fare'], dtype='str')

In [28]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    Lower_fence = Q1 - 1.5*IQR
    print(Q1)
    print(Q3)
    print(Lower_fence)

22.0
35.0
2.5
7.8958
31.0
-26.7605